# Generated by Django 3.2.3 on 2021-11-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0002_auto_20211115_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_existence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventories',
            name='type_action',
            field=models.CharField(blank=True, choices=[('2', 'RETIRAR'), ('1', 'INSERTAR')], max_length=1, null=True),
        ),
    ]
