# Generated by Django 3.2.3 on 2021-11-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0003_auto_20211115_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventories',
            name='type_action',
        ),
        migrations.AddField(
            model_name='inventorieshistory',
            name='type_action',
            field=models.CharField(blank=True, choices=[('1', 'INSERTAR'), ('2', 'RETIRAR')], max_length=1, null=True),
        ),
    ]
